# Generated by Django 3.0.2 on 2021-11-15 15:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '[Answer] Ответ',
                'verbose_name_plural': '[Answer] Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswersQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
            ],
            options={
                'verbose_name': '[AnswersQueue] Очередь ответов',
                'verbose_name_plural': '[AnswersQueue] Очереди ответов',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('link_to_the_profile_photo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '[Characters] Персонажи',
                'verbose_name_plural': '[Characters] Персонажи',
            },
        ),
        migrations.CreateModel(
            name='CharacterSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '[Selected characters] Выбранные персонажи',
                'verbose_name_plural': '[Character Selection] Выбор персонажа',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': '[Check] Ответ',
                'verbose_name_plural': '[Check] Ответы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '[Event] Событие',
                'verbose_name_plural': '[Event] События',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('min_elements', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '[News] Новость',
                'verbose_name_plural': '[News] Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '[NewsElement] Элемент',
                'verbose_name_plural': '[NewsElements] Элементы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '[Order] Подписка',
                'verbose_name_plural': '[Orders] Подписки',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('min_answers', models.IntegerField(default=7)),
                ('version', models.BooleanField(default=False, verbose_name='Бесплатная версия')),
            ],
            options={
                'verbose_name': '[Question] Вопрос',
                'verbose_name_plural': '[Question] Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': '[Rate] Тариф',
                'verbose_name_plural': '[Rates] Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_blogger', models.IntegerField(default=0)),
                ('role_expert', models.IntegerField(default=0)),
                ('role_seller', models.IntegerField(default=0)),
                ('count_users', models.IntegerField(default=0)),
                ('count_orders_all', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '[Statistics] Статистика',
                'verbose_name_plural': '[Statistics] Статистика',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '[Support] Поддержка',
                'verbose_name_plural': '[Support] Обращения пользователей',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('version', models.BooleanField(default=False, verbose_name='Бесплатная версия')),
                ('news', models.BooleanField(default=False)),
                ('count_true_ratings', models.IntegerField(default=0)),
                ('count_all_ratings', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '[Template] Шаблон',
                'verbose_name_plural': '[Template] Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': '[Text] Шаблон текста',
                'verbose_name_plural': '[Text] Шаблоны текстов',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': '[Voucher] Купон',
                'verbose_name_plural': '[Vouchers] Купоны',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='legending.Template')),
            ],
            options={
                'verbose_name': '[Title] Заголовок',
                'verbose_name_plural': '[Title] Заголовки',
            },
        ),
    ]
