# Generated by Django 3.0.2 on 2021-11-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legending', '0004_auto_20211115_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='date_activation',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
    ]
