# Generated by Django 3.0.2 on 2021-11-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legending', '0005_auto_20211115_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='date_activation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to=settings.AUTH_USER_MODEL),
        ),
    ]
